name: jsicp_mobile
description: JSICP Flutter App
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
flutter:
  uses-material-design: true
